########################################
########################################
##
##  Copyright (C) 2015 Korovasoft, Inc.
##
##  File:
##      \file .travis.yml
##
##  Description:
##      \brief Travis-CI configuration file
##
##  Author:
##      \author J. Caleb Wherry
##      \author Robert D. French
##
########################################
########################################

language: 
  - python

install:
  - sudo apt-get install -y python3 python3-pip
  - sudo pip3 install colorama
  - sudo pip3 install nose

before_script:
  # Put installed colorama package in correct place for new python version. This is extremely sloppy and nasty but 
  #  it is the quickest way I could it to work on Travis:
  #- sudo mkdir /usr/local/lib/python3.2/dist-packages/colorama/
  #- sudo cp /usr/local/lib/python2.7/dist-packages/colorama/* /usr/local/lib/python3.2/dist-packages/colorama/

script:
  - nosetests

notifications:
  recipients:
    - calebwherry@gmail.com
    - robert@robertdfrench.me
  email:
    on_success: always
    on_failure: always

